# Generated by Django 5.2.1 on 2025-05-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_groups_remove_user_user_permissions'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('group_name', 'creator'), name='unique_group_per_creator'),
        ),
    ]
