# Generated by Django 5.2.1 on 2025-05-23 10:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskCreated',
            new_name='CreatedTask',
        ),
        migrations.CreateModel(
            name='PlannedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('custom_description', models.TextField(blank=True)),
                ('custom_points', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('state', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('finished', 'Finished')], default='open', max_length=10)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_planned_person', to=settings.AUTH_USER_MODEL)),
                ('assigner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_delivered_person', to=settings.AUTH_USER_MODEL)),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_planned_group', to='api.createdtask')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.DeleteModel(
            name='TaskAssigned',
        ),
        migrations.AddConstraint(
            model_name='plannedtask',
            constraint=models.UniqueConstraint(fields=('task_template', 'start_time'), name='unique_task_assignment_per_time'),
        ),
    ]
