# Generated by Django 5.2.1 on 2025-05-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_taskcreated_createdtask_plannedtask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedtask',
            name='custom_description',
        ),
    ]
