# Generated by Django 5.2.1 on 2025-05-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_plannedtask_custom_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdtask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
