# Generated by Django 5.2.1 on 2025-05-29 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_createdtask_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plannedtask',
            name='unique_task_assignment_per_time',
        ),
        migrations.AlterField(
            model_name='plannedtask',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_tasks', to='api.createdtask'),
        ),
        migrations.AddConstraint(
            model_name='plannedtask',
            constraint=models.UniqueConstraint(fields=('task_template', 'start_time', 'assignee'), name='unique_task_per_time_per_person'),
        ),
    ]
